<!--Start footer-->
<div id="footerContainer">      
 
	<div id="footer">

		<div class="footerlist connect">
		
			<span>Connect</span>

			<ul>
				<li><a href="http://www.environment.nsw.gov.au/contact/socialmedia.htm" title="Twitter" class="f-twitter f-icon"></a></li>
				<li><a class="f-facebook f-icon" title="Facebook" href="http://www.environment.nsw.gov.au/contact/socialmedia.htm"></a></li>
				<li><a href="http://www.environment.nsw.gov.au/contact/socialmedia.htm" title="YouTube" class="f-youtube f-icon"></a></li>
				<li><a href="http://www.environment.nsw.gov.au/contact/socialmedia.htm" title="Flickr" class="f-flickr f-icon"></a></li>
				<li><a href="http://www.environment.nsw.gov.au/contact/socialmedia.htm" title="RSS" class="f-rss f-icon"></a></li>
			</ul>
			
			<a href="http://www.environment.nsw.gov.au/contact/SocialMedia.htm">Social Media Centre</a>
			
			<ul>
				<li>
					<div class="icon-text">
						<a href="http://www.environment.nsw.gov.au/whatsnewarchive/subscribe.htm " title="E-news" class="f-enews f-icon"></a></br>
						<a href="http://www.environment.nsw.gov.au/whatsnewarchive/subscribe.htm">E-news</a>
					</div>
				</li>
				<li>
					<div class="icon-text mob-div">
						<a href="http://www.environment.nsw.gov.au/contact/socialmedia.htm#mobile " class="f-mobile f-icon"></a></br>
						<a href="http://www.environment.nsw.gov.au/contact/socialmedia.htm#mobile ">Mobile</a>
					</div>
				</li>
					<li>
						<div class="icon-text share-div">
							<!-- AddThis Button BEGIN -->
							<a class="show addthis_button f-share f-icon" href="#">
								<img alt="Share" src="http://www.environment.nsw.gov.au/images/footericons/share-inactive.png"/>
							</a>
							<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e7192194bc39d38"></script>
							<script type="text/javascript"> 
							var addthis_config = { 
							data_ga_property: 'UA-1477612-1', 

							data_ga_social : true 
							}; 
							</script>
							<!-- AddThis Button END -->
							<br>
							<a href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=ra-4e7192194bc39d38">Share</a>
						</div>
					</li>
			</ul>
		</div>

		<div class="footerlist items">
			<span>Feedback</span>
			<ul>
				<li><a href="http://www.environment.nsw.gov.au/feedback/">Web support</a></li>
				<li><a href="http://www.environment.nsw.gov.au/consult/">Public consultation</a></li>
			</ul>
		</div>
		
		<div class="footerlist items">
			<span>Contact</span>
			<ul>	
				<li><a href="http://www.environment.nsw.gov.au/contact">Contact us</a></li>
				<!--<li><a href="http://www.environment.nsw.gov.au/askenvironmentapp">Ask Environment Line</a></li>-->
				<li><a href="http://www.environment.nsw.gov.au/contact/onlineservices.htm">Online services</a></li>
				<li><a href="http://www.environment.nsw.gov.au/contact/locations.htm">Offices</a></li>
				<li><a href="http://www.environment.nsw.gov.au/pollution">Report pollution</a></li>
			</ul>
		</div>
		<div class="footerlist items">
			<span>Government</span>
			<ul>
				<li><a href="http://www.nsw.gov.au/">NSW Government</a></li>
				<li><a href="http://www.jobs.nsw.gov.au/">jobs.nsw</a></li>
			</ul>
		</div>
		<div class="footerlist items">
			<span>About</span>
			<ul>
				<li><a href="http://www.environment.nsw.gov.au/help/index.htm">Accessibility</a></li>
				<li><a href="http://www.environment.nsw.gov.au/help/disclaimer.htm">Disclaimer</a></li>
				<li><a href="http://www.environment.nsw.gov.au/help/privacy.htm">Privacy</a></li>
				<li><a href="http://www.environment.nsw.gov.au/help/copyright.htm">Copyright</a></li>
			</ul>
		</div>

	</div>
	
</div>
<script type="text/javascript" src="/js/decc/web-tracker.js"></script>
<!--End footer-->
