<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- some old applications use inc_DECChead inc OEH homepage uses incOEHhomehead inc which will require any updates -->
<link rel="shortcut icon" type="image/vnd.microsoft.icon" href="http://www.environment.nsw.gov.au/favicon.ico" />
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<link rel="stylesheet" type="text/css" href="/css/decc/styles_v3.css"/>
<link rel="stylesheet" type="text/css" href="/css/decc/modules.css"/>
<link rel="stylesheet" type="text/css" media="print" href="/css/decc/print_v2.css"/>

<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery-1.7.2.min.js">/* jQuery */</script>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery.treeview.pack-090504.js">/* jQuery Menu Plugin */</script>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery.hoverIntent.pack-090504.js">/* jQuery Menu Plugin */</script>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery.superfish.pack-090504.js">/* jQuery Menu Plugin */</script>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery.lightbox-0.5.pack-090504.js">/* jQuery Lightbox Plugin */</script>
<!--[if IE 6]>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery.bgiframe.pack-090504.js">/* jQuery IE6 Fix */</script>
<![endif]-->
<script type="text/javascript" charset="utf-8" src="/js/decc/main-090504.js">/* Main Script */</script>

<script type="text/javascript" charset="utf-8" src="/js/decc/resize.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery-ui-1.7.1.min-090504.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/decc/jquery/jquery.jcarousel.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/decc/general.js"></script>
<!--[if IE]>
<link rel="stylesheet" href="/css/decc/ie_v2.css" type="text/css" />
<![endif]-->

<!--[if lte IE 6]>
<link rel="stylesheet" href="/css/decc/ie6.css" type="text/css" />
<![endif]-->

<!--[if gte IE 5.5]>
<link rel="stylesheet" href="/css/decc/ie5.css" type="text/css" />
<![endif]-->

<link rel="home" title="Home" href="http://www.environment.nsw.gov.au/" />
<link rel="copyright" title="Copyright" href="http://www.environment.nsw.gov.au/help/copyright.htm" />
<link rel="help" title="Help" href="http://www.environment.nsw.gov.au/help/index.htm" />
<link rel="search" title="Search" href="http://www.environment.nsw.gov.au/Search/QuickSearch.aspx" />