				<div id="topHead">
                    <div id="department_logo"><a href="http://www.nsw.gov.au"><img src="/images/decc/government_logo.gif" alt="Links to Government Chief Information Office Homepage" /></a><a href="http://www.environment.nsw.gov.au/"><img src="/images/decc/depttitle.gif" alt="Links to Department of Environment, Climate Change and Water Homepage" /></a></div>
                   
					<div id="links">
                        <a href="#content">Skip links</a>&nbsp;|&nbsp;<a href="http://www.environment.nsw.gov.au/contact/">Contact us</a>&nbsp;|&nbsp;<a href="http://www.environment.nsw.gov.au/help/">Help</a>&nbsp;|&nbsp;<a href="http://www.environment.nsw.gov.au/search/subjectindex.htm">A-Z index</a><br />
                        <form method="post" id="frmQuickSearchScreen" action="http://www.environment.nsw.gov.au/Search/QuickSearch.aspx">
                            <input name="quickKeyword" title="Keyword Search" type="text" placeholder="Keyword Search" id="quickKeyword" />
							<input name="StartPage" value="1" type="hidden">
                            <input name="imgSearch" type="image" class="go" id="imgSearch" value="Submit" src="/images/decc/keywordGo.gif" alt="Submit" />
							<input type="hidden" name="as_fid" value="UKJl6zDTS1rhbTbZtNop">
                        </form>
                    </div>
                    <div id="quick-links">
                        <select class="quick-link">
                            <option value="">Quicklinks</option>
<option value="http://goulbwb75/geonetwork210PUBLIC/apps/tabsearch/">Maps and data</option>
                            <option value="http://www.environment.nsw.gov.au/prpoeoapp/searchregister.aspx">Search the POEO public register</option>
                            <option value="http://www.environment.nsw.gov.au/noise/neighbourhoodnoise.htm">Dealing with neighbourhood noise</option>
                            <option value="http://www.environment.nsw.gov.au/noise/nglg.htm">Noise guide for local government</option>
                            <option value="http://www.environment.nsw.gov.au/asmslightprofileapp/default.aspx">Online waste tracking</option>
                            <option value="http://www.environment.nsw.gov.au/asmslightprofileapp/default.aspx">Online waste reporting</option>
                            <option value="http://www.environment.nsw.gov.au/prclmapp/searchregister.aspx">Search contaminated land records</option>
                            <option value="http://www.environment.nsw.gov.au/annualpass/dailyvehicleentryfees.htm">National park entry fees</option>
                            <option value="http://www.environment.nsw.gov.au/households/cleanoutguide.htm">Household Chemical CleanOuts</option>
                            <option value="http://www.rbgsyd.nsw.gov.au/">Botanic gardens</option>
                            <option value="http://www.environment.nsw.gov.au/4cmas/">Catchment management</option>
                            <option value="http://www.mpa.nsw.gov.au/">Marine parks</option>
                            <option value="http://www.environment.nsw.gov.au/water/">Water</option>
                        </select>
						<input name="quick-link-submit" type="image" class="go" id="quick-link-submit" value="Submit" src="http://www.environment.nsw.gov.au/images/admin/quicklinksgo.png" alt="Go" />
                    </div>
					
                </div>