<!-- start incDECCbanner_v2.inc-->
        <div id="topHead">
<div id="department_logo">
                <a href="http://www.nsw.gov.au"><img src="/images/decc/government_logo.gif" width="82" height="62" alt="Link to NSW Government home page"></a>
                <a href="http://www.environment.nsw.gov.au/"><img src="/images/decc/depttitle.gif" width="162" height="62" alt="Link to Office of Environment and Heritage home page"></a>
            </div>
            
                <div id="links">
                    <a href="#content">Skip links</a>&nbsp;|&nbsp;<a href="http://www.environment.nsw.gov.au/contact/">Contact us</a>&nbsp;|&nbsp;<a href="http://www.environment.nsw.gov.au/help/">Help</a>&nbsp;|&nbsp;<a href="http://www.environment.nsw.gov.au/subjectindex.htm">A-Z index</a><br />
                    <!--<form method="post" id="frmQuickSearchScreen" action="http://www.environment.nsw.gov.au/Search/QuickSearch.aspx">
                        <input name="quickKeyword" title="Keyword Search" type="text" placeholder="Keyword Search" id="quickKeyword" />
                        <input name="StartPage" value="1" type="hidden">
                        <input name="imgSearch" type="image" class="go" id="imgSearch" value="Submit" src="/images/decc/keywordGo.gif" alt="Submit" />
                        <input type="hidden" name="as_fid" value="UKJl6zDTS1rhbTbZtNop">
                    </form>-->
                        <script>
                          (function() {
                            var cx = '013828583255245889455:z0s_q_layae';
                            var gcse = document.createElement('script');
                            gcse.type = 'text/javascript';
                            gcse.async = true;
                            gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                                '//www.google.com/cse/cse.js?cx=' + cx;
                            var s = document.getElementsByTagName('script')[0];
                            s.parentNode.insertBefore(gcse, s);
                          })();
                        </script>
                        <gcse:searchbox-only></gcse:searchbox-only>
                </div>
                <div id="quick-links">
                    <select class="quick-link">
                        <option value="">Quicklinks</option>
                        <option value="http://www.environment.nsw.gov.au/askenvironmentlineapp/">Ask Environment Line</option>
			<option value="http://www.environment.nsw.gov.au/annualpass/dailyvehicleentryfees.htm">National park entry fees</option>
                        <option value="http://www.environment.nsw.gov.au/parkmanagement/ParkManagementPlans.htm">Park management plans</option>
                        <option value="http://www.environment.nsw.gov.au/households/cleanoutguide.htm">Household Chemical CleanOuts</option>
			<option value="http://www.environment.nsw.gov.au/water/">Water</option>
                        <option value="http://www.environment.nsw.gov.au/homepower/index.htm">Home power savings program</option>
                        <option value="http://www.rbgsyd.nsw.gov.au/">Botanic gardens</option>
			<option value="http://www.epa.nsw.gov.au">Environment Protection Authority</option>
                        <option value="http://www.dpi.nsw.gov.au/locallandservices/">Local Land Services</option>
                        <option value="http://www.mpa.nsw.gov.au/">Marine parks</option>
                      
			
                    </select>
                    <input name="quick-link-submit" type="image" class="go" id="quick-link-submit" value="Submit" src="http://www.environment.nsw.gov.au/images/admin/quicklinksgo.png" alt="Go" />
                </div>
            
        </div>
<!-- end incDECCbanner_v2.inc-->
