<div id="nav">
	<ul id="topLevelNav" class="clearfix">
		<li class="topLevelNavItem" id="home">
			<a href="http://www.environment.nsw.gov.au/" class="active"><b>Home</b>
			<br>
			</a>
		</li>
		<li class="topLevelNavItem" id="environmental_issues">
			<a href="http://www.environment.nsw.gov.au/environmentalissues.htm" class="active"><b>Environmental</b>
			<br>
			Issues</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/water/">Water</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/air/">Air quality</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/soildegradation/index.htm">Soil degradation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/pestsweeds/">Pests and weeds</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/pollution">Reporting pollution</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="climate_change">
			<a href="http://www.environment.nsw.gov.au/climatechange.htm" class="active"><b>Climate</b>
			<br>
			Change</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/climatesystem.htm">Our climate system</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/impacts.htm">Climate change impacts in NSW</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/adaptation.htm">Adapting to climate change</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/government.htm">NSW Government action</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/emissionsoverview.htm">Overview of NSW emissions</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/energyefficiency.htm">Energy efficiency</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/climatechange/renewableenergy.htm">Renewable energy</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="sustaining_our_environment">
			<a href="http://www.environment.nsw.gov.au/sustainingourenvironment.htm" class="active"><b>Sustaining our</b>
			<br>
			Environment</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/sustainability/index.htm">What is sustainability</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/households/">Sustainable households</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/sustainableschools/">Sustainable Schools NSW</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/sustainbus/">Sustainable business</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/community/">Sustainable communities</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/government/">Sustainable government</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/grants/">Sustainability funding</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/education/">Sustainability education</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="nature_conservation">
			<a href="http://www.environment.nsw.gov.au/natureconservation.htm" class="active"><b>Nature</b>
			<br>
			Conservation</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/biodiversity/index.htm">Conserving biodiversity</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/conservationprograms/">Conservation programs</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/biobanking/">BioBanking</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/animals/">Native animals</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/vegetation/">Native vegetation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/wildlifeatlas/about.htm">Atlas of NSW Wildlife</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/geodiversity/">Geodiversity, karst and caves</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/soils/index.htm">Landscapes and soils</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/threatenedspecies/">Threatened species</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/wildlifelicences/">Wildlife licences</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/protectedareas/">Protected areas</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/fire/">Fire</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/youcanhelp/">How you can help</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="culture_and_heritage">
			<a href="http://www.environment.nsw.gov.au/cultureandheritage.htm" class="active"><b>Culture and</b>
			<br>
			Heritage</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/nswcultureheritage/">Cultures and heritage of NSW</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/achreform/index.htm">Aboriginal heritage law reform</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/heritage/">State heritage</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/chresearch/">Research</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/licences/achregulation.htm">Regulation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/conservation/">Conservation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/licences/">Heritage registers</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/chpublications/">Publications</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="visiting_a_park">
			<a href="http://www.environment.nsw.gov.au/nationalparks/default.aspx" class="active"><b>Visiting</b>
			<br>
			a park</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/parksearchatoz.aspx">Find parks and attractions</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/Facilities.aspx">Find facilities and activities</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/searchCampgrounds.aspx">Find camping</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/searchAccommodation.aspx">Find accommodation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/events.aspx">Upcoming events</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/Tours.aspx">Guided tours with us</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/touroperators.aspx">Commercial tours and activities</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/volunteers/VolunteerNationalPark.htm">Volunteer for NSW national parks</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/annualpass/">Annual passes and vehicle entry fees</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/venuehire/">Hire a venue</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/NationalParks/FireClosure.aspx">Fires, floods and park closures</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/parksafety/">Park safety and other essentials</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/lookingafterparks/">Looking after our parks</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/parks/tourism.htm">Sustainable tourism and visitation</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="knowledge_centre">
			<a href="http://www.environment.nsw.gov.au/knowledgecentre.htm" class="current"><b>Knowledge</b>
			<br>
			Centre</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/askenvironmentlineapp">Ask Environment Line</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/publications/reporting.htm">Statewide environmental reporting</a>
				</li>
				<li class="">
					<a href="http://mapdata.environment.nsw.gov.au/geonetwork/apps/tabsearch/">Maps and data</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/research/">Research</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/knowledgestrategy/index.htm">Knowledge strategy</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/publicregister/">Public registers</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/publications/">Publications</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/forbusiness.htm">For business</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/forgovernment.htm">For state and local government</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/forteachers.htm">For teachers, schools and community educators</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/4cmas/">For catchment management authorities</a>
				</li>
			</ul>
		</li>
		<li class="topLevelNavItem" id="about_us">
			<a href="http://www.environment.nsw.gov.au/aboutus.htm" class="active"><b>About us</b>
			<br>
			</a>
			<ul>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/whoweare/">Who we are</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/contact/">Contact us</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/whoweare/information.htm">Obtaining information</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/performance/">Our environmental performance</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/jobs/">Careers with us</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/volunteers/">Volunteers</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/events/">Events and activities</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/commercial/">Doing business with us</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/consult/">Public consultation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/grantsandfunding/">Grants and funding</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/legislation/">Legislation</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/media/formedia.htm">For media</a>
				</li>
				<li class="">
					<a href="http://www.environment.nsw.gov.au/whatsnewarchive/index.htm">What's new</a>
				</li>
			</ul>
		</li>
	</ul>
</div>